#!/bin/bash

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
dotfiles="gitconfig oh-my-zsh vim bashrc vimrc zshrc tmux.conf config/base16-shell"    # list of files/folders to symlink in homedir
nonDotFiles="bin"
directories="$HOME/.config";

##########

# create dotfiles_old in homedir
mkdir -p $olddir

#Creane directories
mkdir -p $directories

# change to the dotfiles directory
cd $dir

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
for file in $dotfiles; do
    mv ~/.$file $olddir 2>/dev/null
    ln -s $dir/$file ~/.$file
done

for file in $nonDotFiles; do
    mv ~/$file $olddir
    ln -s $dir/$file ~/$file
done

echo "Instalation complete"
